import type { Student, Assignment, Submission } from '@/types'

export let students: Student[] = [
  {
    id: '1',
    firstName: 'Александр',
    lastName: 'Иванов',
    email: 'a.ivanov@university.edu',
    group: 'ИТ-21',
    enrolledAt: '2021-09-01',
    status: 'active',
  },
  {
    id: '2',
    firstName: 'Мария',
    lastName: 'Петрова',
    email: 'm.petrova@university.edu',
    group: 'ИТ-21',
    enrolledAt: '2021-09-01',
    status: 'active',
  },
  {
    id: '3',
    firstName: 'Дмитрий',
    lastName: 'Сидоров',
    email: 'd.sidorov@university.edu',
    group: 'ИТ-22',
    enrolledAt: '2022-09-01',
    status: 'active',
  },
  {
    id: '4',
    firstName: 'Елена',
    lastName: 'Козлова',
    email: 'e.kozlova@university.edu',
    group: 'ИТ-22',
    enrolledAt: '2022-09-01',
    status: 'active',
  },
  {
    id: '5',
    firstName: 'Андрей',
    lastName: 'Новиков',
    email: 'a.novikov@university.edu',
    group: 'ИТ-20',
    enrolledAt: '2020-09-01',
    status: 'graduated',
  },
  {
    id: '6',
    firstName: 'Ольга',
    lastName: 'Морозова',
    email: 'o.morozova@university.edu',
    group: 'ИТ-21',
    enrolledAt: '2021-09-01',
    status: 'inactive',
  },
]

export let assignments: Assignment[] = [
  {
    id: '1',
    title: 'Курсовая работа: Веб-приложение',
    description: 'Разработка полноценного веб-приложения с использованием React и Node.js',
    dueDate: '2025-03-15',
    status: 'open',
    totalSubmissions: 3,
    maxScore: 100,
  },
  {
    id: '2',
    title: 'Курсовая работа: База данных',
    description: 'Проектирование и реализация реляционной базы данных',
    dueDate: '2025-02-28',
    status: 'in_review',
    totalSubmissions: 5,
    maxScore: 100,
  },
  {
    id: '3',
    title: 'Курсовая работа: Мобильное приложение',
    description: 'Разработка мобильного приложения на React Native',
    dueDate: '2025-04-01',
    status: 'open',
    totalSubmissions: 1,
    maxScore: 100,
  },
  {
    id: '4',
    title: 'Курсовая работа: Алгоритмы',
    description: 'Реализация и анализ алгоритмов сортировки и поиска',
    dueDate: '2024-12-15',
    status: 'closed',
    totalSubmissions: 6,
    maxScore: 100,
  },
]

export const submissions: Submission[] = [
  {
    id: '1',
    studentId: '1',
    assignmentId: '1',
    submittedAt: '2025-01-10T14:30:00',
    score: null,
    status: 'pending',
  },
  {
    id: '2',
    studentId: '2',
    assignmentId: '1',
    submittedAt: '2025-01-12T09:15:00',
    score: 85,
    status: 'graded',
  },
  {
    id: '3',
    studentId: '3',
    assignmentId: '2',
    submittedAt: '2025-01-08T16:45:00',
    score: 92,
    status: 'graded',
  },
  {
    id: '4',
    studentId: '4',
    assignmentId: '2',
    submittedAt: '2025-01-09T11:00:00',
    score: null,
    status: 'pending',
  },
  {
    id: '5',
    studentId: '1',
    assignmentId: '4',
    submittedAt: '2024-12-10T10:30:00',
    score: 78,
    status: 'graded',
  },
]
